const config={city:"Warszawa",latitude:52.2297,longitude:21.0122};let keyboardTarget=null,currentPlaylist=null,currentPlaylistName="",currentTrackDuration=0;function $(id){return document.getElementById(id)}
function updateClock(){const now=new Date;$("time").textContent=now.toLocaleTimeString("pl-PL",{hour:"2-digit",minute:"2-digit"});$("date").textContent=now.toLocaleDateString("pl-PL",{weekday:"long",day:"numeric",month:"long"})}
function showScreen(id){hideKeyboard();document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.target===id));$(id).classList.add("active");if(id==="playlists")loadPlaylists();if(id==="devices")loadDevices();toast({home:"Dashboard",spotify:"Spotify",search:"Wyszukiwarka",playlists:"Playlisty",playlistDetail:"Playlista",devices:"Urządzenia",weather:"Pogoda",system:"System"}[id]||id)}
function toast(t){$("toast").textContent=t;clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>$("toast").textContent="System gotowy",3500)}
function buildKeyboard(){const rows=[
[["1","1"],["2","2"],["3","3"],["4","4"],["5","5"],["6","6"],["7","7"],["8","8"],["9","9"],["0","0"]],
[["Q","q"],["W","w"],["E","e"],["R","r"],["T","t"],["Y","y"],["U","u"],["I","i"],["O","o"],["P","p"]],
[["A","a"],["S","s"],["D","d"],["F","f"],["G","g"],["H","h"],["J","j"],["K","k"],["L","l"],["⌫","back","special backspace"]],
[["Z","z"],["X","x"],["C","c"],["V","v"],["B","b"],["N","n"],["M","m"],["Ą","ą","pl"],["Ę","ę","pl"],["Ó","ó","pl"]],
[["Ł","ł","pl"],["Ń","ń","pl"],["Ś","ś","pl"],["Ż","ż","pl"],["Ź","ź","pl"],["spacja","space","special space"],["Szukaj","enter","special enter"]]
];const box=$("keys");box.innerHTML="";rows.forEach(row=>{const rowEl=document.createElement("div");rowEl.className="key-row";row.forEach(k=>rowEl.appendChild(keyButton(k[0],k[1],k[2]||"")));box.appendChild(rowEl)})}
function keyButton(label,value,cls=""){const b=document.createElement("button");b.className="key "+cls;b.textContent=label;b.onclick=()=>pressKey(value);return b}
function openKeyboard(inputId){keyboardTarget=$(inputId);$("keyboard").classList.remove("hidden");updateKeyboardPreview()}
function hideKeyboard(){$("keyboard").classList.add("hidden")}
function updateKeyboardPreview(){$("keyboardPreview").textContent=keyboardTarget?keyboardTarget.value:""}
function pressKey(key){if(!keyboardTarget)return;if(key==="back")keyboardTarget.value=keyboardTarget.value.slice(0,-1);else if(key==="space")keyboardTarget.value+=" ";else if(key==="enter"){hideKeyboard();searchSpotify()}else keyboardTarget.value+=key;updateKeyboardPreview()}
function fmtMs(ms){if(!ms||ms<0)return"0:00";const s=Math.floor(ms/1000),m=Math.floor(s/60),r=String(s%60).padStart(2,"0");return `${m}:${r}`}
function connectSpotify(){window.location.href="/spotify/login"}
async function disconnectSpotify(){await fetch("/api/spotify/logout",{method:"POST"});toast("Spotify rozłączone. Kliknij Autoryzuj.");setTimeout(()=>location.reload(),700)}
async function spotifyControl(action){try{const r=await fetch(`/api/spotify/control/${action}`,{method:"POST"}),d=await r.json();if(!d.ok)toast(d.error||"Spotify: brak aktywnego urządzenia.");setTimeout(loadSpotify,500)}catch(e){toast("Błąd sterowania Spotify")}}
function previewSeek(v){$("spotifyElapsed").textContent=fmtMs(Number(v))}
async function setSpotifySeek(v){try{const r=await fetch(`/api/spotify/seek?position_ms=${Math.round(Number(v))}`,{method:"POST"}),d=await r.json();if(!d.ok)toast(d.error||"Nie udało się przewinąć utworu.");setTimeout(loadSpotify,500)}catch(e){toast("Błąd przewijania utworu")}}
async function setSpotifyVolume(v){try{$("volumeText").textContent=`${v}%`;const r=await fetch(`/api/spotify/volume?value=${v}`,{method:"POST"}),d=await r.json();if(!d.ok)toast(d.error||"Nie udało się zmienić głośności.")}catch(e){toast("Błąd głośności")}}
function setCover(el,url,fallback="🎧",playing=false){el.classList.toggle("playing",!!playing);if(url){el.textContent="";el.style.backgroundImage=`url('${url}')`}else{el.textContent=fallback;el.style.backgroundImage=""}}
async function loadSpotify(){try{const r=await fetch("/api/spotify/status"),data=await r.json();if(!data.connected){$("spotifyStatus").textContent="Spotify ?";$("spotifyTitle").textContent="Spotify";$("spotifyArtist").textContent="Kliknij Autoryzuj.";$("homeTrack").textContent="Spotify";$("homeArtist").textContent="Kliknij Autoryzuj.";setCover($("spotifyCover"),null);setCover($("homeCover"),null);return}$("spotifyStatus").textContent="Spotify ✓";if(!data.playing_track){$("spotifyTitle").textContent="Brak aktywnego utworu";$("spotifyArtist").textContent=data.message||"Włącz muzykę w Spotify.";$("homeTrack").textContent="Brak utworu";$("homeArtist").textContent="Włącz muzykę w Spotify.";$("seekSlider").value=0;$("seekSlider").max=1000;$("spotifyElapsed").textContent="0:00";$("spotifyDuration").textContent="0:00";setCover($("spotifyCover"),null);setCover($("homeCover"),null);return}currentTrackDuration=data.duration_ms||0;$("spotifyTitle").textContent=data.track_name;$("spotifyArtist").textContent=data.artist_name;$("homeTrack").textContent=data.track_name;$("homeArtist").textContent=data.artist_name;$("spotifyPlay").textContent=data.is_playing?"⏸":"▶";$("spotifyElapsed").textContent=fmtMs(data.progress_ms);$("spotifyDuration").textContent=fmtMs(data.duration_ms);$("seekSlider").max=data.duration_ms||1000;$("seekSlider").value=data.progress_ms||0;if(typeof data.volume_percent==="number"){$("volumeSlider").value=data.volume_percent;$("volumeText").textContent=`${data.volume_percent}%`}setCover($("spotifyCover"),data.album_image,"🎧",data.is_playing);setCover($("homeCover"),data.album_image,"🎧",data.is_playing)}catch(e){$("spotifyStatus").textContent="Spotify ?"}}
function escapeHtml(str){return String(str||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderList(container,items,type){container.innerHTML="";if(!items||items.length===0){container.innerHTML=`<p class="muted">Brak wyników.</p>`;return}items.forEach(item=>{const row=document.createElement("div");row.className="result-item";const img=document.createElement("div");img.className="result-img";if(item.image){img.style.backgroundImage=`url('${item.image}')`}else{img.textContent=type==="playlist"?"📚":type==="device"?"🔊":"🎵"}const main=document.createElement("div");main.className="result-main";const title=document.createElement("strong");title.textContent=item.name||"Bez nazwy";const sub=document.createElement("small");sub.textContent=item.subtitle||"";main.appendChild(title);main.appendChild(sub);const btn=document.createElement("button");if(type==="track"){btn.textContent="Play";btn.onclick=()=>playTrack(item.uri)}else if(type==="playlist"){btn.textContent="Otwórz";btn.onclick=()=>openPlaylist(item.id,item.name||"Playlista",item.uri)}else if(type==="playlistTrack"){btn.textContent="Play";btn.onclick=()=>playPlaylistTrack(item.uri)}else if(type==="device"){btn.textContent="Wybierz";btn.onclick=()=>transferDevice(item.id)}row.appendChild(img);row.appendChild(main);row.appendChild(btn);container.appendChild(row)})}
async function searchSpotify(){const q=$("searchInput").value.trim(),box=$("searchResults");if(!q){box.innerHTML=`<p class="muted">Wpisz nazwę utworu.</p>`;return}box.innerHTML=`<p class="muted">Szukam...</p>`;try{const r=await fetch(`/api/spotify/search?q=${encodeURIComponent(q)}`),data=await r.json();if(data.error){box.innerHTML=`<p class="muted">${escapeHtml(data.error)}</p>`;return}renderList(box,data.items,"track")}catch(e){box.innerHTML=`<p class="muted">Błąd wyszukiwania.</p>`}}
async function loadPlaylists(){const box=$("playlistResults");box.innerHTML=`<p class="muted">Ładuję playlisty...</p>`;try{const r=await fetch("/api/spotify/playlists"),data=await r.json();if(data.error){box.innerHTML=`<p class="muted">${escapeHtml(data.error)}</p>`;return}renderList(box,data.items,"playlist")}catch(e){box.innerHTML=`<p class="muted">Błąd pobierania playlist.</p>`}}
async function openPlaylist(id,name,uri){currentPlaylist=uri;currentPlaylistName=name;$("playlistTitle").textContent=name;$("playlistTracks").innerHTML=`<p class="muted">Ładowanie utworów...</p>`;showScreen("playlistDetail");try{const r=await fetch(`/api/spotify/playlist/${encodeURIComponent(id)}/tracks`),data=await r.json();if(data.error){$("playlistTracks").innerHTML=`<p class="muted">${escapeHtml(data.error)}</p>`;return}renderList($("playlistTracks"),data.items,"playlistTrack")}catch(e){$("playlistTracks").innerHTML=`<p class="muted">Błąd otwierania playlisty.</p>`}}
async function loadDevices(){const box=$("deviceResults");box.innerHTML=`<p class="muted">Ładuję urządzenia...</p>`;try{const r=await fetch("/api/spotify/devices"),data=await r.json();if(data.error){box.innerHTML=`<p class="muted">${escapeHtml(data.error)}</p>`;return}renderList(box,data.items,"device")}catch(e){box.innerHTML=`<p class="muted">Błąd pobierania urządzeń.</p>`}}
async function postJSON(url,payload){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});return r.json()}
async function playTrack(uri){const d=await postJSON("/api/spotify/play-track",{uri});toast(d.ok?"Odtwarzam utwór":(d.error||"Nie udało się odtworzyć."));showScreen("spotify");setTimeout(loadSpotify,800)}
async function playCurrentPlaylist(){if(!currentPlaylist){toast("Nie wybrano playlisty");return}const d=await postJSON("/api/spotify/play-context",{uri:currentPlaylist});toast(d.ok?"Odtwarzam playlistę":(d.error||"Nie udało się odtworzyć."));showScreen("spotify");setTimeout(loadSpotify,800)}
async function playPlaylistTrack(trackUri){const d=await postJSON("/api/spotify/play-from-context",{context_uri:currentPlaylist,track_uri:trackUri});toast(d.ok?"Odtwarzam utwór z playlisty":(d.error||"Nie udało się odtworzyć."));showScreen("spotify");setTimeout(loadSpotify,800)}
async function transferDevice(id){const d=await postJSON("/api/spotify/transfer",{id});toast(d.ok?"Urządzenie wybrane":(d.error||"Nie udało się wybrać urządzenia."));showScreen("spotify");setTimeout(loadSpotify,800)}
function codeIcon(c){if(c===0)return"☀️";if([1,2].includes(c))return"🌤️";if(c===3)return"☁️";if([45,48].includes(c))return"🌫️";if([51,53,55,61,63,65,80,81,82].includes(c))return"🌧️";if([71,73,75,77,85,86].includes(c))return"❄️";if([95,96,99].includes(c))return"⛈️";return"🌤️"}
function codeText(c){if(c===0)return"Bezchmurnie";if([1,2].includes(c))return"Częściowe zachmurzenie";if(c===3)return"Pochmurno";if([45,48].includes(c))return"Mgła";if([51,53,55].includes(c))return"Mżawka";if([61,63,65,80,81,82].includes(c))return"Deszcz";if([71,73,75,77,85,86].includes(c))return"Śnieg";if([95,96,99].includes(c))return"Burza";return"Pogoda"}
async function loadWeather(){try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${config.latitude}&longitude=${config.longitude}&current=temperature_2m,weather_code,wind_speed_10m&timezone=auto`,r=await fetch(url),data=await r.json(),cur=data.current,temp=Math.round(cur.temperature_2m),code=cur.weather_code,wind=Math.round(cur.wind_speed_10m);$("weatherTile").textContent=`${temp}°C`;$("weatherTemp").textContent=`${temp}°C`;$("weatherDesc").textContent=codeText(code);$("weatherIcon").textContent=codeIcon(code);$("homeWeatherIcon").textContent=codeIcon(code);$("wind").textContent=`${wind} km/h`;$("city").textContent=config.city}catch(e){$("weatherDesc").textContent="Brak połączenia"}}
function setBar(id,value,max=100){const el=$(id),w=Math.max(1,Math.min(100,(value/max)*100));el.style.width=`${w}%`;el.style.background=w>80?"var(--red)":w>60?"var(--warn)":"var(--green)"}
function formatUptime(s){const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);if(h>24){const d=Math.floor(h/24);return `${d}d ${h%24}h`}return `${h}h ${m}m`}
async function loadSystem(){try{const r=await fetch("/api/system"),data=await r.json(),temp=Number(data.cpu_temp).toFixed(1),cpu=Math.round(data.cpu_percent),ram=Math.round(data.ram_percent);$("tempTile").textContent=`${temp}°C`;$("topTemp").textContent=`CPU ${temp}°C`;$("cpuTemp").textContent=`${temp}°C`;$("cpuLoad").textContent=`${cpu}%`;$("ram").textContent=`${ram}%`;$("uptime").textContent=formatUptime(data.uptime_seconds);setBar("tempBar",Number(temp),85);setBar("cpuBar",cpu);setBar("ramBar",ram);$("wifi").textContent=data.online?"Wi‑Fi ✓":"Wi‑Fi ?"}catch(e){$("wifi").textContent="Wi‑Fi ?"}}
buildKeyboard();updateClock();setInterval(updateClock,1000);loadWeather();setInterval(loadWeather,600000);loadSystem();setInterval(loadSystem,3000);loadSpotify();setInterval(loadSpotify,2000);
